image: atlassian/default-image:3

definitions:
  steps:
    - - step: &init-env-variables
          name: Init env variables
          script:
            # init env variables
            - export SLOT_NAME="asgard-party"
            - export TAG=$BITBUCKET_TAG
            - export CONTAINER_REGISTRY=rg.fr-par.scw.cloud/ejaw
            - export IMAGE=$CONTAINER_REGISTRY/$SLOT_NAME-server:$TAG
            # writing variables into build.env
            - echo export TAG=$TAG >> build.env
            - echo export CONTAINER_REGISTRY=$CONTAINER_REGISTRY >> build.env
            - echo export IMAGE=$IMAGE >> build.env
          artifacts:
            - build.env
    - step: &build-and-push
        name: Build and push image
        services:
          - docker
        script:
          - source build.env
          - docker login $CONTAINER_REGISTRY -u nologin -p $SCW_SECRET_TOKEN
          - docker build --build-arg TAG=$TAG --build-arg SSH_KEY="`cat /opt/atlassian/pipelines/agent/data/id_rsa`" -t $IMAGE -f Dockerfile .
          - docker push $IMAGE


#################################################################
# List of pipelines
#################################################################
pipelines:
  tags:
    '*.*.*':
      - step: *init-env-variables
      - step: *build-and-push